### ISSUE TITLE
Why some important tasks are marked to ignore_errors ?

### ISSUE THREAD

**Issue by bew** [zzet/ansible-rbenv-role#133]
Reading [tasks/user_install.yml](https://github.com/zzet/ansible-rbenv-role/blob/d456082abe016a6cd9a0c12772650eaca54f9e70/tasks/user_install.yml), I see that almost all tasks (13/15) are marked with `ignore_errors: yes`, why is that?

For exemple I wouldn't want a failure to install X ruby version to simply be ignored silently. So what's the reasoning behind this?

Would you accept a PR that removes all non-necessary `ignore_errors` ?

**Comment by chriscz** [comment]
I was just bitten by this. Would you consider changing these lines @zzet ? I've just started using this role, super glad you created it!

**Comment by zzet** [comment]
Hey folks!

It comes with this commit https://github.com/zzet/ansible-rbenv-role/commit/f56ffff541797cc3feb1f1457841a9009646bc11. 

I don't remember exact reason, but I don't see the requirement to ignore errors. Feel you free to send PR with improvement ;)
