### ISSUE TITLE
Remove {{ rbenv.ruby_version }} from names

### ISSUE THREAD

**Issue by pmackay** [zzet/ansible-rbenv-role#19]
According to https://github.com/ansible/ansible/issues/3103 its correct behaviour that they dont get printed, and I dont see the values being filled in when I'm using this role. So it gets a bit confusing.

**Comment by pmackay** [comment]
@zzet would it be helpful if I did a PR for this?

**Comment by zzet** [comment]
@pmackay yes, of course. Sorry, I am in the last time little busy.

**Comment by pmackay** [comment]
Closing cos having updated to ansible v2, it seems to now insert the variables!
