### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by DanyHunter** [zzet/ansible-rbenv-role#29]
I am getting the following error when running zzet.rbenv:

`TASK: [zzet.rbenv | homebrew_tap tap=homebrew/dupes state=present] ************`
`fatal: [default] => error while evaluating conditional: rbenv.ruby_version <= 1.9.3-p0`

It seems that I cannot override the `ruby_version` variable as well. Maybe I'm doing something wrong.

**Comment by xenocid** [comment]
Exactly the same thing here:
TASK: [zzet.rbenv | homebrew_tap tap=homebrew/dupes state=present] ************
fatal: [localhost] => error while evaluating conditional: rbenv.ruby_version <= 1.9.3-p0

**Comment by zzet** [comment]
Hi @DanyHunter @xenocid.

You do not have enough opportunities to override the only version of ruby?

What about `error while evaluating conditional` - which ansible version you are use?

**Comment by DanyHunter** [comment]
1.8.2

I define `2.2.0` as the ruby_version but it still tries to install 1.9.3-p0, even though by default it should install a higher version right?

**Comment by zzet** [comment]
@DanyHunter I'll fix bug with ruby_version tomorrow.

**Comment by zzet** [comment]
@DanyHunter @xenocid this commit https://github.com/zzet/ansible-rbenv-role/commit/d20505cd0f4202d137468b43e303dd069f6b7031 fix error for me (ansible 1.8.3)
