### ISSUE TITLE
Ruby version 2.2.0 failing on checkout

### ISSUE THREAD

**Issue by BrandonMathis** [zzet/ansible-rbenv-role#32]
When I run the rbenv role on my box, which has rbenv already installed by this galaxy role, I get this error.

```
failed: [104.236.6.108] => (item={'repo': 'git://github.com/sstephenson/ruby-build.git', 'version': '2.2.0', 'name': 'ruby-build'}) => {"failed": true, "item": {"name": "ruby-build", "repo": "git://github.com/sstephenson/ruby-build.git", "version": "2.2.0"}}
msg: Failed to checkout 2.2.0
```

I think this is because the latest version of ruby-build is not being cloned down.

**Comment by zzet** [comment]
@BrandonMathis Can you provide more information?

https://travis-ci.org/zzet/ansible-rbenv-role#L484-L488

**Comment by zzet** [comment]
@BrandonMathis all is well?

**Comment by leonelgalan** [comment]
@BrandonMathis the 2.2.0 is the problem in here. This is ruby-build version, not ruby's so it should look more like: `v20150130`. Cross check your `rbenv_plugins` variable against the _defaults/main.yml_ 

https://github.com/zzet/ansible-rbenv-role/blob/master/defaults/main.yml#L11

**Comment by BrandonMathis** [comment]
Sorry @zzet, I actually found the issues and it was due to a change that one of our devs made to our playbook.
