### ISSUE TITLE
1.3.0 fails to set ruby version

### ISSUE THREAD

**Issue by mkllnk** [zzet/ansible-rbenv-role#50]
The main task `tasks/main.yml` doesn't set the Ruby version. Instead of running `rbenv global {{ rbenv.ruby_version }} && rbenv rehash` it runs the install command a second time.

I will try a newer version. A fix in version 1.3.1 would be nice.

**Comment by zzet** [comment]
Hi @mkllnk! Can you try 2.1.6?

**Comment by mkllnk** [comment]
Yes, that worked. We are using 2.1.6 now. I had to change the users variable and apply #51. That was all. Are you planning a 1.3.1 release with a fix or are you declaring the 1.3 release as unsupported? You can add the wontfix label and close the issue then.
Thank you!

**Comment by zzet** [comment]
@mkllnk I bump version after every fix or feature in role. Support old versions is difficult for me.
