### ISSUE TITLE
2.1.8 not on ansible galaxy

### ISSUE THREAD

**Issue by BrandonMathis** [zzet/ansible-rbenv-role#56]
Hey @zzet, forgive me because I have never published to ansible galaxy before and may not understand their approval process/your versioning process but I see you have a tag for 2.1.8 but that version is not on ansible galaxy.

https://galaxy.ansible.com/detail#/role/102

Is there a reason for that? Should I not try to install the 2.1.8 tag?

**Comment by zzet** [comment]
@BrandonMathis sorry, role was not imported ![](http://puu.sh/mDeVn/df2d95a239.png). At now all is ok!
