### ISSUE TITLE
clean up after version change

### ISSUE THREAD

**Issue by ringe** [zzet/ansible-rbenv-role#97]
I have these variables:

    rbenv:
    env: user
    version: v1.0.0
    ruby_version: 2.3.1

So I want to upgrade to ruby_version: 2.4.1

There maybe should be a task to remove / clean up old ruby versions?

**Comment by zzet** [comment]
@ringe Thank you for idea. 

I'm not sure what necessary to automatically remove the `old` ruby version. If the commune considers it necessary, I do not mind. And welcome for PR.

**Comment by zzet** [comment]
Released with https://github.com/zzet/ansible-rbenv-role/pull/100
